### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by vee-huyvunguyen** [DurianDan/learn_rust#1]
- This is where I record my learning process

**Comment by vee-huyvunguyen** [comment]
### Learned:
- Macros are ways for automatically **editing code** at **compile time.**
- Macros are like **decorators in Python** but _more powerful_.
- When defining types,`impl` are like `Partial<>` in **TypeScript**
- Learned a way for application to handle `.env` config file with **hierarchy**.
### TODO:
- [x] Continue the tutorial video from minute [9:00 ](https://youtu.be/e37NbhSm56o?list=PLECOtlti4Psr4hXVX5GuSvLKp0-RZjz93&t=541)
- [x] Understand how and why Rust needs to use the keyword `move` in the closure, when the `pool` var is used

**Comment by vee-huyvunguyen** [comment]
## Learned:
- `Procedural Macros` generate codes, so other macros can be used within code **without explicitly importing or defining**
- In a **cargo project,** only the `main.rs` file's got to use the `mod` key word, acknowledging other `.rs` files to only be **modules**. 

## TODO
- [x] Finnish the to-do app video from [11:55](https://youtu.be/e37NbhSm56o?list=PLECOtlti4Psr4hXVX5GuSvLKp0-RZjz93&t=716)

**Comment by vee-huyvunguyen** [comment]
## Learned: 
- This is a suitable framework for having **a single server** for every service, as the **docker image** can be **under 100MB** of size.
- See the **implicit functionalities** of the **attribute macros** (`pg_mapper`) when converting query results (`Iter<TokioPostgresRow>>`) into vector of structs (`Vec<TodoList>>`) (details in `handlers.rs` and `models.rs`)

## TODO
- [ ] finish the [final video][1]
- [ ] Start building the API for the project [MLOps-Marathon-2023
][2]

[1]:https://www.youtube.com/watch?v=3vMxuM7ezEk&list=PLECOtlti4Psr4hXVX5GuSvLKp0-RZjz93&index=3
[2]:https://github.com/DurianDan/demo2-mlops-workflow
